"use server";

import crypto from "crypto";
import { db } from "@/lib/db";
import { blogs, clients, generatedPosts } from "@/lib/db/schema";
import { and, asc, desc, eq, gte, inArray, isNotNull, isNull, lt, ne, or, sql } from "drizzle-orm";
import { requireAdmin } from "@/lib/auth/helpers";
import {
  generateContent,
  ideateTopic,
  suggestKeywords,
  estimateImageCostUsd,
  type GenerateOptions,
  type Tone,
} from "@/lib/services/content-generator";
import { getActiveKnowledgeForBlog } from "@/lib/actions/knowledge-actions";
import {
  assignProfileForBlogIfPeptides,
  getStyleProfileForBlog,
} from "@/lib/actions/style-profile-actions";
import { publishPost, backfillPostSeo, resolveShopifyBlogId, type PlatformBlog } from "@/lib/services/platform-client";
import { verticalForNiche } from "@/lib/content/verticals";
import { loadNicheProfiles } from "@/lib/content/niche-registry";
import { resolveNicheConfig } from "@/lib/content/niche-config-db";
import { effectiveBlogCta, blogDomainCtaUrl } from "@/lib/content/cta-target";
import { deriveBrandName } from "@/lib/content/brand";
import { hasPlaceholders, interpolatePromptPlaceholders } from "@/lib/content/prompt-placeholders";
import {
  claimKeywordTargetForBlog,
  markKeywordTargetGenerated,
  markKeywordTargetFailed,
  markKeywordTargetSkipped,
  releaseKeywordTargetClaim,
  releaseStuckKeywordTargets,
  type ClaimedKeywordTarget,
} from "@/lib/actions/keyword-target-actions";
import { isTransientFailure, utcDayKey } from "@/lib/content/publish-slots";
import { shardForBlog } from "@/lib/cron/sharding";
import { blogHasCredentials } from "@/lib/cron/cadence";
import { logActivity } from "@/lib/services/activity-logger";
import {
  formatPostingPlan,
  isoWeekdayUtc,
  normalizePostingPlan,
  postsPerWeek,
  quotaForDate,
  WEEKDAY_NAMES,
} from "@/lib/posting-plan";
import {
  getIdeationCandidatesForBlog,
  isQueryCoveredByBlog,
  recordCoveredQuery,
} from "@/lib/content/topic-candidates";
import { findMostSimilarTitle } from "@/lib/content/topic-similarity";
import { ctaColorHex } from "@/lib/content/cta-colors";
import { resolveNextPostLanguage } from "@/lib/content/post-language";
import { getAppBaseUrl } from "@/lib/services/link-tracker";
import { pingIndexNowFireAndForget } from "@/lib/services/index-now-pinger";
import { scanPostAfterPublishFireAndForget } from "@/lib/services/post-seo-runner";
import {
  findTopicalLinkRefs,
  relinkAfterPublishFireAndForget,
} from "@/lib/services/semantic-linking";
import { toCanonicalUrl } from "@/lib/services/canonical-url";
import {
  logScrubberVerdict,
  shouldHoldForReview,
  scrubberSummary,
  SCRUBBER_HOLD_PREFIX,
} from "@/lib/content/scrubber";
import {
  runWithTelemetry,
  withBlog,
  bumpCounter,
  setCounter,
  setCurrentPostId,
  snapshotCounters,
  currentRunId,
  recordPipelineError,
  type RunCounters,
} from "@/lib/services/run-telemetry";

// ─── Types ──────────────────────────────────────────────────────────────────

export interface GenerateAndPublishInput {
  blogId: string;
  topic?: string;
  keywords?: string[];
  wordCount?: number;
  tone?: Tone;
  isAutoGenerated?: boolean;
  /**
   * When set, hyperlink the first occurrence of one of these buy-phrases/terms
   * in the article's opening paragraph to the site's money URL (tracked
   * redirect). Used by peptide location pages for the funnel link.
   */
  buyLinkTerms?: string[];
}

export interface GenerateAndPublishResult {
  success: boolean;
  /**
   * The generated_posts row this run created. Empty string when the run never
   * created one — i.e. status "skipped", where another process already holds
   * this blog's publishing slot for the UTC day.
   */
  generatedPostId: string;
  /**
   * "skipped" = the day-slot claim was lost to a concurrent run (T08). Not a
   * failure: the other run is publishing this blog right now.
   */
  status: "published" | "generated" | "failed" | "skipped";
  /**
   * True when the failure looks retryable inside the same cron tick (rate
   * limit, upstream 5xx, network blip).
   *
   * This field exists because runGenerateAndPublish CATCHES its own errors
   * and RETURNS a result: everything from generation onward sits inside the
   * try block and is swallowed by its catch. A caller that only inspects
   * thrown errors therefore never sees the dominant failure class, which is
   * exactly the bug that made the retry in publishOneInner dead code. Always
   * false on success and on "skipped".
   */
  transient: boolean;
  externalPostId?: string | number;
  externalPostUrl?: string;
  message: string;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

/** Start of the current UTC day (used for the per-day cap). */
function startOfUtcDay(now: Date): Date {
  return new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), now.getUTCDate()));
}

/**
 * How many publishing slots this blog already holds for a UTC day (T08).
 *
 * Occupying statuses are 'generating' / 'publishing' (in flight) and
 * 'published' (done) — exactly the predicate of the
 * generated_posts_blog_day_slot_uniq index, so the number this returns is the
 * next free slot. 'generated' (article written, platform publish failed) and
 * 'failed' are excluded so a broken attempt frees its slot for a retry on the
 * next tick.
 *
 * Counts ONLY rows that carry a publish_day, i.e. auto-publish claims. Manual
 * posts (publish_day null) are counted by the cadence gate in
 * runAutoPublishCron, not by the slot allocator. Mixing them in would make the
 * next slot number depend on when a human happened to click "Generate", so two
 * racing sweeps could compute DIFFERENT slots and both succeed — which is the
 * exact failure this whole task exists to prevent.
 */
async function countClaimedSlotsForDay(
  blogId: string,
  publishDay: string,
): Promise<number> {
  const [row] = await db
    .select({ n: sql<number>`count(*)::int` })
    .from(generatedPosts)
    .where(
      and(
        eq(generatedPosts.blogId, blogId),
        eq(generatedPosts.publishDay, publishDay),
        inArray(generatedPosts.status, ["generating", "publishing", "published"]),
      ),
    );
  return row?.n ?? 0;
}

/**
 * Safety floor between two publishes on the same blog. The auto-publish cron
 * ticks hourly (render.yaml: "0 * * * *"), so this is what actually spaces
 * multi-post days apart, and it also stops a manual cron poke from shipping
 * two posts back-to-back.
 */
const MIN_HOURS_BETWEEN_POSTS = 6;

/**
 * Hard cap on how many blogs a single cron run will publish to. Prevents a
 * single run from monopolizing the function's maxDuration (300s) when many
 * blogs are due at once — the rest get picked up on the next cron run.
 *
 * Each blog takes ~25-35s end-to-end (Claude content + image scene +
 * Nano Banana + scrubber + platform publish). 25 × 30s = 12.5min, but
 * because runGenerateAndPublish is awaited sequentially and the maxDuration
 * is 300s, only ~10 blogs actually finish in one run. The cap below is a
 * soft upper bound that prevents the loop from queuing more work than it
 * can complete.
 */
const MAX_BLOGS_PER_CRON_RUN = Number(
  process.env.MAX_BLOGS_PER_CRON_RUN || "50",
);

/**
 * Per-tick concurrency: how many blogs run in parallel inside a single
 * cron tick. Default 3 (safe vs. Anthropic 50 RPM and Google 60 RPM
 * when combined with 4 shards = 12 simultaneous publishes). Clamped to
 * 1..8. Override on the web service via env var.
 */
void process.env.AUTO_PUBLISH_INTER_BLOG_DELAY_MS; // legacy env, no longer read

/**
 * Width of the daily publishing window, in hourly cron ticks.
 *
 * Preferred hours are drawn from 0..PUBLISH_WINDOW_HOURS-1 rather than 0..23
 * so that EVERY blog has several ticks of runway before the UTC day rolls
 * over. With the old 0..23 range a blog hashed to hour 23 had exactly one
 * chance per scheduled day; if that tick was over the per-run cap, or the
 * function deadline cut the run short, the post was lost until the next
 * matching weekday (the cadence policy is strict day-only, no catch-up — see
 * isBlogDueForPost). At 18 the worst slot still gets 7 ticks.
 *
 * Raising this back toward 24 re-introduces the starvation; lowering it
 * increases per-hour publish density. 18 keeps peak in-flight publishes
 * (4 shards x AUTO_PUBLISH_CONCURRENCY) inside the API headroom.
 */
const PUBLISH_WINDOW_HOURS = 18;

/**
 * Deterministic preferred publishing hour (0..PUBLISH_WINDOW_HOURS-1 UTC)
 * for a blog, derived from its UUID. Same blog => same hour, forever. This
 * is what spreads publishes across the day so multiple due blogs don't all
 * hit the Shopify / Anthropic / Google APIs in the same minute.
 *
 *   blog A (uuid c26a8...) -> hour 9    (publishes at 09:00 UTC on its days)
 *   blog B (uuid f12d3...) -> hour 14   (publishes at 14:00 UTC on its days)
 *   blog C (uuid 4a9b2...) -> hour 4    (publishes at 04:00 UTC on its days)
 *
 * The cron only considers a blog due once the current hour has reached or
 * passed the blog's preferred hour. Late cron runs (cron paused, server
 * restart, etc.) still catch up within the same UTC day — a blog scheduled
 * for 09:00 that the cron sees at 14:00 still gets published, because 14 >= 9.
 */
function preferredHourForBlog(blogId: string): number {
  const hex = crypto
    .createHash("sha1")
    .update(blogId)
    .digest("hex")
    .slice(0, 8);
  return parseInt(hex, 16) % PUBLISH_WINDOW_HOURS;
}

/** Reason a blog is or isn't due. */
type DueDecision =
  | { due: true }
  | { due: false; reason: string };

/**
 * Cadence eligibility against the canonical posting plan. Does NOT check the
 * per-client total cap (that needs a separate query, done in
 * runAutoPublishCron).
 *
 * blogs.posting_plan is an integer[7]: entry i = posts wanted on ISO weekday
 * i+1, UTC. See src/lib/posting-plan.ts. This single field replaced
 * posting_frequency / posting_frequency_days / posts_per_day, which used to
 * be three sources of truth that disagreed.
 *
 * Order of checks:
 *   1. Empty plan            -> not schedulable. Should be unreachable here:
 *                               runAutoPublishCron filters empty plans out at
 *                               the DB layer and alerts on them separately.
 *                               Kept as a belt-and-braces guard.
 *   2. Today's quota is 0    -> today is not one of the blog's weekdays.
 *   3. Quota already met     -> enough posts for today already shipped.
 *   4. MIN_HOURS_BETWEEN_POSTS safety floor against the real last publish.
 *
 * Semantics are unchanged from the previous day-array behaviour: a plan of
 * [1,0,1,0,1,0,0] permits exactly one post on Mon/Wed/Fri. A plan of
 * [2,2,2,2,2,2,2] permits two per day, six hours apart — which is what the
 * old "2 posts per day" posting_frequency string did.
 */
function isBlogDueForPost(
  blog: typeof blogs.$inferSelect,
  todaysPublishedCount: number,
  now: Date = new Date(),
  // The blog's REAL last-publish time, sourced from
  // MAX(generated_posts.published_at WHERE status='published').
  // CRITICAL: do NOT use blog.lastPostVerifiedAt here — that field is
  // reset every 6h by the post-verification cron whenever it confirms
  // live posts, which would make the safety floor think the blog just
  // posted and skip it forever. Only an actual publish through our
  // system advances this timestamp.
  lastPublishedAt: Date | null = null,
): DueDecision {
  const last = lastPublishedAt;
  const hour = 1000 * 60 * 60;

  const plan = normalizePostingPlan(blog.postingPlan);

  // 1. No schedule at all. This is a configuration fault, not a routine
  //    skip — runAutoPublishCron reports it as `unscheduledActiveBlogs`
  //    and /api/notifications raises it as a critical item.
  if (postsPerWeek(plan) === 0) {
    return {
      due: false,
      reason:
        "no posting plan configured — blogs.posting_plan is empty; " +
        "set posting days on the blog before activating it",
    };
  }

  const today = isoWeekdayUtc(now);
  const quotaToday = quotaForDate(plan, now);

  // 2. Strict day filter. Today MUST carry a non-zero quota. No catch-up,
  //    no bypass: a missed day waits for the next scheduled weekday.
  if (quotaToday === 0) {
    return {
      due: false,
      reason: `today is ${WEEKDAY_NAMES[today - 1]}; scheduled days are [${formatPostingPlan(plan)}]`,
    };
  }

  // 3. Daily quota.
  if (todaysPublishedCount >= quotaToday) {
    return {
      due: false,
      reason: `daily quota hit (${todaysPublishedCount}/${quotaToday} today)`,
    };
  }

  // 4. Safety floor against rapid-fire posts (cron poke / manual trigger
  //    races, and the gap between two posts on a multi-post day).
  if (last) {
    const hoursSince = (now.getTime() - last.getTime()) / hour;
    if (hoursSince < MIN_HOURS_BETWEEN_POSTS) {
      return {
        due: false,
        reason: `${hoursSince.toFixed(1)}h since last post < ${MIN_HOURS_BETWEEN_POSTS}h safety floor`,
      };
    }
  }

  return { due: true };
}

/**
 * Titles ideation should steer clear of: this blog's OWN recent titles (listed
 * first so they survive ideateTopic's internal cap) PLUS its SIBLING blogs'
 * recent titles (other blogs of the same client). Feeding the network's titles
 * in is the cross-blog diversity guard — it stops a client's sites converging on
 * the same topic when they publish around the same time, since the scraped
 * keyword pool is shared client-wide. Deduped case-insensitively, own-first.
 */
export async function getRecentTitles(
  blogId: string,
  clientId: string,
  opts: { own?: number; siblings?: number } = {},
): Promise<string[]> {
  const ownLimit = opts.own ?? 12;
  const siblingLimit = opts.siblings ?? 12;

  const [ownRows, siblingRows] = await Promise.all([
    db
      .select({ title: generatedPosts.title })
      .from(generatedPosts)
      .where(eq(generatedPosts.blogId, blogId))
      .orderBy(desc(generatedPosts.createdAt))
      .limit(ownLimit),
    db
      .select({ title: generatedPosts.title })
      .from(generatedPosts)
      .where(
        and(
          eq(generatedPosts.clientId, clientId),
          ne(generatedPosts.blogId, blogId),
        ),
      )
      .orderBy(desc(generatedPosts.createdAt))
      .limit(siblingLimit),
  ]);

  const seen = new Set<string>();
  const titles: string[] = [];
  for (const r of [...ownRows, ...siblingRows]) {
    const title = r.title?.trim();
    if (!title) continue;
    const key = title.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    titles.push(title);
  }
  return titles;
}

/**
 * The duplicate-detection corpus for a ledger-claimed title: the blog's own +
 * sibling recent titles PLUS its permanent covered-topic history. Same corpus
 * ideateTopic builds internally — the ledger path previously had none at all.
 */
async function buildLedgerDedupCorpus(
  blogId: string,
  clientId: string,
): Promise<string[]> {
  const [recent, candidateSet] = await Promise.all([
    getRecentTitles(blogId, clientId),
    getIdeationCandidatesForBlog(blogId),
  ]);
  return Array.from(
    new Set(
      [...recent, ...candidateSet.coveredTopics]
        .map((t) => t.trim())
        .filter(Boolean),
    ),
  );
}

/**
 * Pick the published sibling posts the generator may weave into the article
 * body as inline <a href> anchors.
 *
 * Selection is TOPICAL, not chronological: findTopicalLinkRefs scores every
 * published sibling with the same hybrid (dense cosine + sparse full-text)
 * formula the Related-posts engine uses, reusing embeddings that already exist
 * on those rows. Two of the eight slots stay reserved for the most recent
 * posts so brand-new pages keep accruing inbound internal links.
 *
 * Recency-only ordering (the previous behaviour) produced a chronological
 * chain instead of topical clusters, so no pillar structure could form.
 *
 * URLs are canonicalised: external_post_url is the PLATFORM url, which on
 * Shopify is xyz.myshopify.com.
 *
 * Falls back to the old recency query if the topical path returns nothing or
 * throws — a missing internal-link block is worse than a chronological one.
 */
async function getInternalLinkRefs(
  blog: typeof blogs.$inferSelect,
  opts: {
    topic: string;
    keywords?: string[];
    language?: string | null;
    limit?: number;
    /** Regenerate path: don't offer a post its own URL as a link target. */
    excludePostId?: string;
  },
): Promise<Array<{ title: string; url: string }>> {
  const limit = opts.limit ?? 8;

  try {
    const refs = await findTopicalLinkRefs({
      blogId: blog.id,
      canonicalDomain: blog.domain,
      topic: opts.topic,
      keywords: opts.keywords ?? [],
      language: opts.language ?? null,
      limit,
      recentSlots: 2,
      excludePostId: opts.excludePostId,
    });
    if (refs.length > 0) {
      return refs.map(({ title, url }) => ({ title, url }));
    }
  } catch (err) {
    console.warn(
      `[internal-links] topical selection failed for ${blog.domain}: ` +
        `${err instanceof Error ? err.message : "unknown"} — using recency`,
    );
  }

  const rows = await db
    .select({
      id: generatedPosts.id,
      title: generatedPosts.title,
      url: generatedPosts.externalPostUrl,
    })
    .from(generatedPosts)
    .where(
      and(
        eq(generatedPosts.blogId, blog.id),
        eq(generatedPosts.status, "published"),
        isNotNull(generatedPosts.externalPostUrl),
        isNotNull(generatedPosts.title),
        opts.excludePostId ? ne(generatedPosts.id, opts.excludePostId) : undefined,
      ),
    )
    .orderBy(desc(generatedPosts.publishedAt))
    .limit(limit);

  return rows.flatMap((r) =>
    r.title && r.url
      ? [{ title: r.title, url: toCanonicalUrl(r.url, blog.domain) }]
      : [],
  );
}

// ─── Core: generate + publish for one blog ──────────────────────────────────

export async function runGenerateAndPublish(
  input: GenerateAndPublishInput,
): Promise<GenerateAndPublishResult> {
  // 1. Load blog + client (for niche)
  const [row] = await db
    .select({
      blog: blogs,
      clientNiche: clients.niche,
      clientLanguageMode: clients.languageMode,
      clientCustomPrompt: clients.customPrompt,
      clientStackPersona: clients.stackPersona,
      ctaEnabled: clients.ctaEnabled,
      ctaLabel: clients.ctaLabel,
      ctaUrl: clients.ctaUrl,
      ctaPlacement: clients.ctaPlacement,
      ctaColor: clients.ctaColor,
      registrationEnabled: clients.registrationFormEnabled,
      registrationPlacement: clients.registrationFormPlacement,
    })
    .from(blogs)
    .innerJoin(clients, eq(blogs.clientId, clients.id))
    .where(eq(blogs.id, input.blogId))
    .limit(1);

  if (!row) throw new Error(`Blog ${input.blogId} not found`);
  const { blog, clientNiche } = row;
  // Custom prompts are client-wide: one prompt drives all of a client's blogs.
  // Mutable — may be re-interpolated below when it contains {keyword}/{city}
  // placeholders (see docs/local-keyword-content-plan.md §6).
  let customPrompt = row.clientCustomPrompt?.trim() || undefined;
  // When that prompt is active, optionally keep each blog's per-blog persona
  // layered on top of it (client-level toggle).
  const applyPersona = Boolean(customPrompt) && Boolean(row.clientStackPersona);
  const cta = effectiveBlogCta({
    niche: clientNiche,
    blogDomain: blog.domain,
    ctaEnabled: row.ctaEnabled,
    ctaLabel: row.ctaLabel,
    ctaUrl: row.ctaUrl,
    ctaPlacement: row.ctaPlacement,
    ctaColor: row.ctaColor,
  });

  if (!blogHasCredentials(blog)) {
    throw new Error(
      `Blog ${blog.domain} is missing ${blog.platform} credentials — connect the platform first`,
    );
  }

  // 2. Load (or lazily assign) the blog's locked style profile FIRST so
  //    it can flow into both topic ideation AND article generation.
  //    Without passing the profile into ideateTopic, every peptide
  //    blog's first post defaulted to BPC-157 (the first item in the
  //    generic peptides keyTopics list). The profile gives each blog a
  //    UNIQUE primary-compounds pair to anchor on.
  let styleProfile = await getStyleProfileForBlog(blog.id);
  if (!styleProfile) {
    const r = await assignProfileForBlogIfPeptides(blog.id);
    if (r.success && r.assigned) {
      styleProfile = await getStyleProfileForBlog(blog.id);
    }
  }
  if (styleProfile) {
    console.info(
      `[auto-publish] Using style profile for ${blog.domain}: ` +
        `voice V${styleProfile.voiceId}, skeleton S${styleProfile.skeletonId}, ` +
        `cadence ${styleProfile.cadenceId}, sub-niche ${styleProfile.subNicheId}, ` +
        `strictness=${styleProfile.scrubberStrictness}, ` +
        `primary=${styleProfile.primaryCompounds.join("+")}`,
    );
  } else {
    console.info(
      `[auto-publish] No style profile for ${blog.domain} (niche="${clientNiche ?? "none"}") — using legacy prompt path`,
    );
  }

  // 3. Resolve topic + keywords (auto-ideate if not supplied). Pass the
  //    style profile so the topic anchors on this blog's unique
  //    primary-compounds + locked sub-niche.
  // Resolve the vertical + post language ONCE so the topic and the
  // article share a language. Bilingual (en_fr) verticals coin-flip to
  // one concrete language for this post.
  const verticalForPost = verticalForNiche(clientNiche);
  // Per-client language toggle wins (en / fr / strict en_fr alternation);
  // unset falls back to the legacy TLD/niche/vertical derivation.
  const postLanguage = await resolveNextPostLanguage({
    languageMode: row.clientLanguageMode,
    blogId: blog.id,
    verticalLanguage: verticalForPost?.language,
    domain: blog.domain,
    niche: clientNiche,
  });

  // Distilled client Knowledge Base for this blog (client-wide + per-blog
  // active documents). Anchors ideation on the client's own material.
  const knowledge = await getActiveKnowledgeForBlog(blog.id);

  let topic = input.topic?.trim();
  let keywords = input.keywords ?? [];

  // Local keyword-targeted content (see docs/local-keyword-content-plan.md).
  // Claim the best pending keyword target for this blog — only when the
  // caller hasn't already supplied an explicit topic, the same gate
  // ideateTopic uses below (a manual "Generate now" with an explicit topic
  // keeps full control). No city, or an empty ledger, and this resolves to
  // undefined — the feature's on/off switch, enforced here too, not just in
  // the builder.
  const claimedTarget: ClaimedKeywordTarget | undefined = topic
    ? undefined
    : await claimKeywordTargetForBlog(blog.id);

  const brandName = blog.brandName || deriveBrandName(blog.domain) || undefined;
  const localTarget = claimedTarget
    ? {
        keyword: claimedTarget.keyword,
        city: claimedTarget.city,
        region: blog.region,
        countryCode: blog.countryCode,
        brandName,
        brandUrl: blogDomainCtaUrl(blog.domain) ?? undefined,
      }
    : undefined;

  // Custom prompts can reference {keyword}/{city}/{region}/{country}/
  // {brand}/{domain} — the brief keeps its existing top-priority authority
  // over topic/voice, it just gains the ability to pull these from the
  // database. Only attempted when the prompt actually contains a
  // placeholder, so this is a no-op, byte-identical customPrompt for every
  // client that doesn't use one.
  if (customPrompt && hasPlaceholders(customPrompt)) {
    customPrompt = await interpolatePromptPlaceholders(
      customPrompt,
      {
        clientId: blog.clientId,
        domain: blog.domain,
        city: blog.city,
        region: blog.region,
        countryCode: blog.countryCode,
        niche: clientNiche,
      },
      claimedTarget,
      brandName,
    );
  }

  // Tracks whether the post that ends up published actually targeted the
  // claimed keyword — set only when attempt 1 (below) succeeds using
  // localTarget. A fallback recovery attempt (a re-ideated, unrelated topic)
  // still publishes fine, but never covers the claimed keyword, so the
  // ledger row must go back to 'failed' (retryable) rather than 'generated'.
  let generatedViaLocalTarget = false;

  // The query this post covers + the sub-questions the article must answer.
  // Both are recorded on the post row and, once published, in
  // blog_covered_queries so this blog can never re-cover the subject.
  let primaryQuery: string | null = null;
  let supportingQueries: string[] = [];

  if (!topic) {
    if (claimedTarget) {
      // The local-keyword ledger used to bypass duplicate detection entirely:
      // it took claimedTarget.topicTitle verbatim with no similarity check.
      // Ledger titles are template-built from a CLIENT-WIDE keyword pool, so
      // two near-identical scraped keywords produce two near-identical titles
      // on the same blog. Check it against the same corpus ideation uses; on a
      // hit, retire the ledger row and fall through to ideation.
      const ledgerCorpus = await buildLedgerDedupCorpus(blog.id, blog.clientId);
      const ledgerDup = findMostSimilarTitle(claimedTarget.topicTitle, ledgerCorpus);
      const alreadyCovered = await isQueryCoveredByBlog(blog.id, claimedTarget.keyword);
      if (ledgerDup || alreadyCovered) {
        const why = ledgerDup
          ? `title duplicates "${ledgerDup.title}" (${Math.round(ledgerDup.score * 100)}% word overlap)`
          : `keyword "${claimedTarget.keyword}" is already covered by this blog`;
        console.info(
          `[runGenerateAndPublish] skipping keyword target ${claimedTarget.id} for ${blog.domain}: ${why}`,
        );
        await markKeywordTargetSkipped(claimedTarget.id, why);
      } else {
        topic = claimedTarget.topicTitle;
        primaryQuery = claimedTarget.keyword;
        if (keywords.length === 0) keywords = [claimedTarget.keyword];
      }
    }

    if (!topic) {
      const recentTitles = await getRecentTitles(blog.id, blog.clientId);
      const ideated = await ideateTopic(clientNiche, recentTitles, {
        verticalKey: verticalForPost?.key ?? null,
        styleProfile: styleProfile ?? undefined,
        language: postLanguage,
        knowledge,
        customPrompt,
        blogId: blog.id,
      });
      if (ideated.exhausted) {
        // Deliberate: refusing to publish beats publishing a known duplicate.
        // publishOne() treats this as non-transient (no retry) and records it
        // in the run results, which is exactly the signal an operator needs —
        // this blog wants a keyword refresh, not another post.
        throw new Error(
          `Topic ideation exhausted for ${blog.domain} — every demand-validated ` +
            `candidate is already covered. Refresh this client's keyword pool ` +
            `(/api/cron/refresh-keywords or a DataForSEO pull) before it can publish again.`,
        );
      }
      topic = ideated.topic;
      primaryQuery = ideated.primaryQuery;
      supportingQueries = ideated.supportingQueries;
      if (keywords.length === 0) keywords = ideated.keywords;
      if (ideated.groundedIn === "fallback") {
        console.warn(
          `[runGenerateAndPublish] ${blog.domain}: topic was NOT grounded in query data ` +
            `(client has no scraped keyword pool)`,
        );
      }
    }
  }

  if (!topic) throw new Error("Could not resolve a topic to write about");

  // 4. Claim this blog's publishing slot for the UTC day, then insert the
  //    pending row that tracks the attempt (T08).
  //
  //    THE CLAIM *IS* THE INSERT. A partial unique index on
  //    (blog_id, publish_day, day_slot) WHERE status IN
  //    ('generating','publishing','published') means only one process can
  //    ever hold a given slot. `ON CONFLICT DO NOTHING ... RETURNING` gives
  //    us the winner/loser answer in a single round-trip, which is not a
  //    stylistic choice: src/lib/db/index.ts builds the client on
  //    drizzle-orm/neon-http, and the Neon HTTP driver has no interactive
  //    session — SELECT ... FOR UPDATE followed by an INSERT in one
  //    transaction is simply not available here.
  //
  //    day_slot exists because a blog may legitimately publish more than
  //    once a day: a posting_plan entry may be greater than 1, and
  //    isBlogDueForPost permits todaysPublishedCount < that quota. Slot n
  //    is the (n+1)-th post of the day. countClaimedSlotsForDay counts only
  //    rows that already hold a slot for this day, so two racing processes
  //    always compute the SAME next slot and exactly one wins the insert.
  //
  //    On a lost claim we do NOT retry with slot+1. A legitimate second post
  //    of the day is picked up by the next hourly tick, which will count the
  //    in-flight row and claim slot 1 naturally. Bumping the slot here would
  //    recreate the duplicate this guard exists to prevent, at the cost of at
  //    most one hour of latency for multi-post-per-day blogs.
  //
  //    Manual generation (isAutoGenerated false — the admin "Generate"
  //    button) deliberately claims nothing: publish_day stays null, NULLs
  //    never collide in a unique index, and an operator asking for an extra
  //    post today still gets one. This guard exists to stop an accidentally
  //    re-invoked cron, not a human.
  const claimedAt = new Date();
  const publishDay = utcDayKey(claimedAt);
  let generatedPostId: string;

  if (input.isAutoGenerated) {
    const daySlot = await countClaimedSlotsForDay(blog.id, publishDay);
    const [claimed] = await db
      .insert(generatedPosts)
      .values({
        blogId: blog.id,
        clientId: blog.clientId,
        topic,
        keywords,
        primaryQuery,
        supportingQueries,
        status: "generating",
        language: postLanguage,
        isAutoGenerated: true,
        publishDay,
        daySlot,
        createdAt: claimedAt,
        updatedAt: claimedAt,
      })
      .onConflictDoNothing()
      .returning({ id: generatedPosts.id });

    if (!claimed) {
      // Another process owns (blog, publishDay, daySlot). In practice this is
      // a re-invoked cron shard racing a sweep that is still in flight. Hand
      // the keyword target straight back to the pool — we never generated
      // anything against it, so it keeps its priority position.
      if (claimedTarget) {
        await releaseKeywordTargetClaim(
          claimedTarget.id,
          `Publishing slot ${daySlot} for ${publishDay} was already claimed by another run`,
        );
      }
      const message =
        `slot ${daySlot} for ${publishDay} already claimed by another run — ` +
        "skipping to avoid a duplicate post";
      console.warn(`[auto-publish] ${blog.domain}: ${message}`);
      recordPipelineError({
        site: "auto-publish.claimSlot",
        code: "PUBLISH_SLOT_CLAIM_LOST",
        severity: "warn",
        message: `${blog.domain}: ${message}`,
        blogId: blog.id,
        clientId: blog.clientId,
        context: { domain: blog.domain, publishDay, daySlot },
      });
      return {
        success: false,
        generatedPostId: "",
        status: "skipped",
        transient: false,
        message,
      };
    }
    generatedPostId = claimed.id;
  } else {
    const [pending] = await db
      .insert(generatedPosts)
      .values({
        blogId: blog.id,
        clientId: blog.clientId,
        topic,
        keywords,
        primaryQuery,
        supportingQueries,
        status: "generating",
        language: postLanguage,
        isAutoGenerated: false,
      })
      .returning({ id: generatedPosts.id });
    generatedPostId = pending.id;
  }
  // Attach the post id to the current telemetry frame so everything the
  // generator records below — truncation salvage, imageless, scrubber —
  // is joinable to this generated_posts row. No-op outside a cron run.
  setCurrentPostId(generatedPostId);

  try {
    // 5. Generate content using the style profile loaded in step 2.
    //    Resolve vertical so the generator can pull recent news headlines
    //    as external-link sources for non-peptide posts.
    //    Pre-fetch TOPICALLY-RELATED sibling posts on this blog so the
    //    generator can weave internal links into the article. `let`, not
    //    `const`: the topic-recovery loop below can swap the topic out, and the
    //    link candidates have to follow it.
    let internalLinkRefs = await getInternalLinkRefs(blog, {
      topic,
      keywords,
      language: postLanguage,
    });
    // Zero refs means the article will be generated with no internal-link
    // clause at all. Normal for a blog's first few posts; a persistent
    // fleet-wide rate means externalPostUrl is not being recorded, which
    // is a publish-path bug, not a cold start. See T16.
    if (internalLinkRefs.length === 0) {
      bumpCounter("linkingSkipped");
      recordPipelineError({
        site: "auto-publish.internalLinks",
        code: "INTERNAL_LINKS_UNAVAILABLE",
        severity: "warn",
        message: `No published sibling posts with a URL on ${blog.domain} — article will have zero internal links`,
        blogId: blog.id,
        clientId: blog.clientId,
        postId: generatedPostId,
        context: { domain: blog.domain },
      });
    }

    // Niche config from the editable `niches` DB table (falls back to code
    // when there's no row). Resolved once here, reused across topic retries.
    const resolvedNiche = await resolveNicheConfig(clientNiche);

    // Build genOpts as a function so the topic-recovery loop below can
    // reuse it with a fresh ideated topic on failure. useLocalTarget is
    // false on any recovery attempt (a re-ideated, unrelated topic must not
    // be forced to also target the original claimed keyword — see
    // generatedViaLocalTarget above).
    const buildGenOpts = (
      t: string,
      kw: string[],
      useLocalTarget: boolean,
    ): GenerateOptions => ({
      topic: t,
      keywords: kw,
      wordCount: input.wordCount ?? 1000,
      tone: input.tone ?? "professional",
      niche: clientNiche,
      resolvedNiche,
      customPrompt,
      applyPersona,
      seoOptimized: true,
      styleProfile: styleProfile ?? undefined,
      verticalKey: verticalForPost?.key ?? null,
      language: postLanguage,
      blogSeed: blog.id,
      // utm_source for the direct CTA / money links (T02).
      blogDomain: blog.domain,
      // Operator-confirmed store name only — NOT the deriveBrandName()
      // suggestion used for localTarget/placeholders above (brand.ts:1-14).
      brandName: blog.brandName,
      internalLinkRefs,
      knowledgeSummaries: knowledge.summaries,
      // Consumed by the article prompt in T05. Inert until then.
      supportingQueries,
      localTarget: useLocalTarget ? localTarget : undefined,
      cta,
      // T02: the money link points at the client's real destination, not at
      // /r/{postId}. Same target the redirect resolved to at click time — the
      // client's CTA URL, or (peptides) the blog's own domain. An empty string
      // is safe: injectMoneyLink no-ops on anything that isn't http(s).
      buyLink: input.buyLinkTerms?.length
        ? {
            url: cta?.url ?? blogDomainCtaUrl(blog.domain) ?? "",
            terms: input.buyLinkTerms,
          }
        : undefined,
      registrationForm: row.registrationEnabled
        ? {
            actionUrl: `${getAppBaseUrl()}/api/register/${blog.id}`,
            placement: row.registrationPlacement ?? "bottom",
            color: ctaColorHex(row.ctaColor) ?? undefined,
          }
        : undefined,
      postId: generatedPostId,
    });

    // Generation with topic-level recovery. Some subjects fail
    // repeatedly — Claude can refuse certain peptide names (returns no
    // text content), or persist in shape-drift even after the inner
    // shape retry. Rather than fail the post, re-ideate a fresh topic
    // that excludes the failing one and try once more.
    // Preload generated niche profiles so getNicheContext() inside the
    // generator sees auto-generated niches (audience/voice/keyTopics). Memoized.
    await loadNicheProfiles();

    const MAX_TOPIC_ATTEMPTS = 2;
    let currentTopic = topic;
    let currentKeywords = keywords;
    let content: Awaited<ReturnType<typeof generateContent>> | undefined;
    const topicFailures: Array<{ topic: string; error: string }> = [];

    for (let attempt = 1; attempt <= MAX_TOPIC_ATTEMPTS; attempt++) {
      try {
        console.info(
          `[runGenerateAndPublish] attempt ${attempt}/${MAX_TOPIC_ATTEMPTS} for ${blog.domain}: "${currentTopic}"`,
        );
        content = await generateContent(
          buildGenOpts(currentTopic, currentKeywords, attempt === 1),
        );
        if (attempt === 1 && claimedTarget) generatedViaLocalTarget = true;
        if (attempt > 1) {
          console.info(
            `[runGenerateAndPublish] recovered on attempt ${attempt} with new topic`,
          );
        }
        break;
      } catch (genErr) {
        const msg =
          genErr instanceof Error ? genErr.message : "Generation failed";
        topicFailures.push({ topic: currentTopic, error: msg });
        recordPipelineError({
          site: "auto-publish.topicAttempt",
          code: "TOPIC_ATTEMPT_FAILED",
          severity: "warn",
          message: `attempt ${attempt} failed for "${currentTopic}": ${msg.slice(0, 200)}`,
          postId: generatedPostId,
          context: { attempt, topic: currentTopic },
        });

        if (attempt === MAX_TOPIC_ATTEMPTS) {
          // Out of budget — rethrow so the outer catch marks the row
          // failed with the combined error message.
          const combined = topicFailures
            .map((a) => `"${a.topic}": ${a.error}`)
            .join(" | ");
          throw new Error(
            `All ${MAX_TOPIC_ATTEMPTS} topic attempts failed — ${combined}`,
          );
        }

        // Re-ideate, excluding the failed topic. If ideation itself
        // throws, fall through to the outer catch.
        const recent = await getRecentTitles(blog.id, blog.clientId);
        const newIdea = await ideateTopic(
          clientNiche,
          [currentTopic, ...recent],
          {
            verticalKey: verticalForPost?.key ?? null,
            styleProfile: styleProfile ?? undefined,
            language: postLanguage,
            knowledge,
            customPrompt,
            blogId: blog.id,
          },
        );
        if (newIdea.exhausted) {
          throw new Error(
            "Re-ideation exhausted: every demand-validated candidate for this blog is already covered",
          );
        }
        if (!newIdea.topic || newIdea.topic.trim() === currentTopic.trim()) {
          throw new Error("Re-ideation returned an empty or duplicate topic");
        }
        currentTopic = newIdea.topic;
        currentKeywords =
          newIdea.keywords.length > 0 ? newIdea.keywords : currentKeywords;
        // The recovery topic replaces the original subject entirely.
        primaryQuery = newIdea.primaryQuery;
        supportingQueries = newIdea.supportingQueries;
        // The recovery attempt writes about something else, so the topical
        // link candidates picked for the ABANDONED topic no longer apply.
        // Costs one more embedding call on a path that is already re-running
        // full article generation.
        internalLinkRefs = await getInternalLinkRefs(blog, {
          topic: currentTopic,
          keywords: currentKeywords,
          language: postLanguage,
        });
        // Reflect the new topic on the pending row so the dashboard
        // shows what the recovery attempt is actually writing about.
        await db
          .update(generatedPosts)
          .set({
            topic: currentTopic,
            keywords: currentKeywords,
            primaryQuery,
            supportingQueries,
            updatedAt: new Date(),
          })
          .where(eq(generatedPosts.id, generatedPostId));
        console.info(
          `[runGenerateAndPublish] re-ideated topic: "${currentTopic}"`,
        );
      }
    }
    if (!content) {
      // Loop guarantees content is set or we throw. Defensive guard.
      throw new Error(
        "Generation loop exited without content (this should be unreachable)",
      );
    }

    // Cost log — per-post breakdown so the operator can spot drift fast.
    {
      const textCost = Number(content.costUsd) || 0;
      const imageCount =
        (content.heroImageUrl ? 1 : 0) + (content.bodyImageUrl ? 1 : 0);
      const perImage = estimateImageCostUsd();
      const imageCost = imageCount * perImage;
      const total = textCost + imageCost;
      console.info(
        `[cost] ${blog.domain}: text=$${textCost.toFixed(4)} ` +
          `(${content.tokensUsed} tok), ` +
          `images=$${imageCost.toFixed(4)} (${imageCount}× @ $${perImage.toFixed(2)}), ` +
          `total=$${total.toFixed(4)}`,
      );
    }

    await db
      .update(generatedPosts)
      .set({
        status: "publishing",
        title: content.title,
        body: content.content,
        excerpt: content.excerpt,
        metaTitle: content.metaTitle,
        metaDescription: content.metaDescription,
        keywords: content.keywords,
        wordCount: content.wordCount,
        seoScore: content.seoScore,
        readabilityScore: content.readabilityScore,
        brandVoiceScore: content.brandVoiceScore,
        tokensUsed: content.tokensUsed,
        costUsd: content.costUsd.toString(),
        scrubberReport: content.scrubberReport ?? null,
        flaggedForReview: content.flaggedForReview ?? false,
        generatedAt: new Date(),
        updatedAt: new Date(),
      })
      .where(eq(generatedPosts.id, generatedPostId));

    // Shadow-mode instrument (T07). In "shadow" — the default — this prints
    // held=true for posts that enforcement WOULD stop, while the post still
    // publishes, so a week of logs answers "what fraction of the network
    // does the gate stop?" before anything is actually blocked.
    logScrubberVerdict({
      domain: blog.domain,
      generatedPostId,
      strictness: styleProfile?.scrubberStrictness ?? null,
      verdict: content.scrubberVerdict,
      flaggedForReview: content.flaggedForReview ?? false,
      report: content.scrubberReport,
    });

    // 4b. THE GATE (T07). Until now shouldHoldForReview() had no caller: the
    //     enforcement module, its mode switch and its tests all shipped, but
    //     nothing in either publish path consulted it, so SCRUBBER_ENFORCEMENT
    //     =enforce changed nothing except one word in the log line above.
    //     This is the call that makes the verdict actually gate publishing.
    //
    //     The row is parked as 'generated' — "the article exists, it is not
    //     live" — and NOT 'publishing'/'published'. That choice is load-
    //     bearing for T08: 'generated' sits outside the
    //     generated_posts_blog_day_slot_uniq predicate, so a held post
    //     releases its day slot instead of silently blocking the blog from
    //     publishing anything until midnight UTC. flaggedForReview is already
    //     true on the row (written in the update above), which is what the
    //     review queue filters on.
    if (shouldHoldForReview(content.flaggedForReview ?? false)) {
      const summary = scrubberSummary(content.scrubberReport);
      const heldMessage = `${SCRUBBER_HOLD_PREFIX} ${summary}`;
      await db
        .update(generatedPosts)
        .set({
          status: "generated",
          failureReason: heldMessage,
          updatedAt: new Date(),
        })
        .where(eq(generatedPosts.id, generatedPostId));

      // The article never went live, so the claimed keyword was not covered.
      // Same treatment as the publish-failure path below. (Both currently
      // land the ledger row in a terminal 'failed' state — that is the
      // draining bug T10 owns; this path deliberately does not diverge from
      // its neighbour ahead of that fix.)
      if (claimedTarget) {
        await markKeywordTargetFailed(claimedTarget.id, heldMessage);
      }

      recordPipelineError({
        site: "auto-publish.scrubberGate",
        code: "SCRUBBER_PUBLISH_HELD",
        severity: "warn",
        message: `${blog.domain}: ${heldMessage}`,
        blogId: blog.id,
        clientId: blog.clientId,
        postId: generatedPostId,
        context: {
          domain: blog.domain,
          verdict: content.scrubberVerdict ?? null,
          strictness: styleProfile?.scrubberStrictness ?? null,
        },
      });
      bumpCounter("scrubberHeld");

      return {
        success: false,
        generatedPostId,
        status: "generated",
        // A scrubber rejection is deterministic — the same prompt would
        // produce another flagged draft. Never retry it inside the tick.
        transient: false,
        message: heldMessage,
      };
    }

    // 5. Publish via platform-client (handles WP + Shopify)
    const platformBlog: PlatformBlog = {
      platform: blog.platform,
      wpUrl: blog.wpUrl,
      wpUsername: blog.wpUsername,
      wpAppPassword: blog.wpAppPassword,
      // SEO plugin routes WordPress meta title/description to Yoast vs
      // RankMath at publish time. Detected during connection test.
      seoPlugin: blog.seoPlugin,
      // Shopify — pass *all* auth fields so buildShopifyCreds picks the right
      // mode. Omitting shopifyAuthMode/clientId/clientSecret made client-
      // credentials blogs fail with "Client ID and Client Secret are required".
      shopifyAuthMode: blog.shopifyAuthMode,
      shopifyStoreUrl: blog.shopifyStoreUrl,
      shopifyAdminApiToken: blog.shopifyAdminApiToken,
      shopifyClientId: blog.shopifyClientId,
      shopifyClientSecret: blog.shopifyClientSecret,
    };

    const publish = await publishPost(platformBlog, {
      title: content.title,
      content: content.content,
      excerpt: content.excerpt,
      status: "publish",
      tags: content.keywords,
      featuredImageUrl: content.heroImageUrl,
      metaTitle: content.metaTitle,
      metaDescription: content.metaDescription,
    });

    if (!publish.success) {
      await db
        .update(generatedPosts)
        .set({
          status: "generated",
          failureReason: `Publish failed: ${publish.message}`,
          updatedAt: new Date(),
        })
        .where(eq(generatedPosts.id, generatedPostId));

      // The article was written but never went live, so the claimed
      // keyword was never actually covered — back to the pool for a
      // future run rather than stuck 'generating'.
      if (claimedTarget) {
        await markKeywordTargetFailed(claimedTarget.id, `Publish failed: ${publish.message}`);
      }

      return {
        success: false,
        generatedPostId,
        status: "generated",
        // The article exists and only the platform call failed. Flagged so
        // the caller can log it, but publishOneInner deliberately does NOT
        // regenerate on this — that would pay for the article twice and
        // orphan the first draft. The draft can be pushed later with
        // blog-actions.publishGeneratedPost().
        transient: isTransientFailure(publish.message),
        message: `Generated but publish failed: ${publish.message}`,
      };
    }

    // 6. Mark published, update blog's last-post tracking
    const publishedAt = new Date();

    // Was the SEO title/description actually written? An absent metaStatus
    // means the platform adapter has not been taught to report it, which is
    // the same operational risk as an explicit "unverified". See T14.
    if (publish.metaStatus !== "written") {
      bumpCounter("metaWriteUnverified");
      recordPipelineError({
        site: "auto-publish.metaWrite",
        code: "META_WRITE_UNVERIFIED",
        severity: publish.metaStatus === "failed" ? "error" : "warn",
        message: `Published to ${blog.domain} with metaStatus=${publish.metaStatus ?? "absent"}`,
        blogId: blog.id,
        clientId: blog.clientId,
        postId: generatedPostId,
        context: {
          domain: blog.domain,
          platform: blog.platform,
          seoPlugin: blog.seoPlugin,
          metaStatus: publish.metaStatus ?? null,
        },
      });
    }
    // What the LIVE page actually rendered after the meta write (T14).
    // null means "could not check" — Shopify, or the page was unreachable.
    const seoMetaVerified = publish.seoMetaVerified ?? null;
    await db
      .update(generatedPosts)
      .set({
        status: "published",
        externalPostId: publish.postId != null ? String(publish.postId) : null,
        externalPostUrl: publish.postUrl ?? null,
        seoMetaVerified,
        seoMetaVerifiedAt: seoMetaVerified === null ? null : publishedAt,
        publishedAt,
        updatedAt: publishedAt,
      })
      .where(eq(generatedPosts.id, generatedPostId));

    if (seoMetaVerified === false) {
      console.error(
        `[auto-publish] SEO META NOT LIVE for ${blog.domain} post ` +
          `${publish.postId} (${publish.postUrl}): ${publish.seoMetaMessage ?? "no detail"}`,
      );
    }

    await db
      .update(blogs)
      .set({
        lastPostVerifiedAt: publishedAt,
        lastPostTitle: content.title,
        updatedAt: publishedAt,
      })
      .where(eq(blogs.id, blog.id));

    // 7. Push notification — IndexNow ping covers Bing, Yandex, Seznam,
    //    Naver, Yep, and DuckDuckGo in one POST. Fire-and-forget: the
    //    publish has already succeeded, so a slow/failed engine ping must
    //    not roll back or delay anything.
    //    The first publish per blog also deploys the blog's OWN IndexNow key
    //    to the document root via the NetGrid MU-plugin, and verifies the
    //    file is actually served before pinging (T15). Subsequent publishes
    //    hit a TTL cache. Shopify is sitemap-only and records a "skipped"
    //    event — see docs/indexnow/README.md.
    //    Google is NOT covered here: it has never supported IndexNow and its
    //    unauthenticated sitemap ping was retired in 2023. The Google path is
    //    Search Console sitemap submission (indexing-onboarding.ts).
    if (publish.postUrl) {
      pingIndexNowFireAndForget(blog, publish.postUrl, generatedPostId);
    }

    // Per-post SEO scan — audit this specific page now that it's live.
    // Fire-and-forget so it never delays or fails the auto-publish run.
    scanPostAfterPublishFireAndForget(generatedPostId);

    // 7b. Semantic linking — embed this post, inject its "Related posts" block
    //     (Shopify: the custom.netgrid_related_posts metafield; WordPress: an
    //     idempotent in-body block), then refresh its top neighbours so the NEW
    //     post appears in THEIR related lists too. That backward+forward pair
    //     is what keeps the internal link graph bidirectional; without it a
    //     cron-published post waited for the hourly backfill and its older
    //     siblings never linked forward at all — and the cron IS the dominant
    //     publish path, so lane B effectively never fired in production.
    //
    //     Must come after the row is stamped status='published' with its
    //     external ids above: applyRelatedLinks bails with "Post is not live"
    //     otherwise.
    //
    //     Fire-and-forget and internally try/caught; no-op when
    //     OPENAI_API_KEY is unset or SEMANTIC_LINK_ON_PUBLISH=0.
    relinkAfterPublishFireAndForget(generatedPostId);

    // Local keyword-targeted content: the ledger row is 'generated' only
    // when the LIVE post actually targeted the claimed keyword (attempt 1
    // with localTarget). A fallback recovery attempt published successfully
    // too, just not on this keyword — back to the pool, retryable.
    if (claimedTarget) {
      if (generatedViaLocalTarget) {
        await markKeywordTargetGenerated(claimedTarget.id, generatedPostId);
      } else {
        await markKeywordTargetFailed(
          claimedTarget.id,
          "Fell back to a re-ideated topic after the keyword-target attempt failed",
        );
      }
    }

    // Permanent coverage record. Written only after the post is LIVE, so a
    // failed generation or publish leaves the query in the pool for a future
    // run. Never throws — see recordCoveredQuery.
    if (primaryQuery) {
      await recordCoveredQuery({
        blogId: blog.id,
        clientId: blog.clientId,
        query: primaryQuery,
        topic: content.title || topic,
        generatedPostId,
        source: claimedTarget ? "ledger" : "ideation",
      });
    }

    return {
      success: true,
      generatedPostId,
      status: "published",
      transient: false,
      externalPostId: publish.postId,
      externalPostUrl: publish.postUrl,
      message: `Published "${content.title}" to ${blog.domain}`,
    };
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    await db
      .update(generatedPosts)
      .set({
        status: "failed",
        failureReason: message,
        updatedAt: new Date(),
      })
      .where(eq(generatedPosts.id, generatedPostId));

    if (claimedTarget) {
      await markKeywordTargetFailed(claimedTarget.id, message);
    }

    return {
      success: false,
      generatedPostId,
      status: "failed",
      // This is THE return site the worker pool's retry could never see:
      // everything from the pending insert onward is inside the try this
      // catch closes, so an Anthropic 429 lands here as a value, not a throw.
      transient: isTransientFailure(message),
      message,
    };
  }
}

/** Resolve a client's CTA columns into a generation-ready CTA (or undefined). */
/** Build the platform credential bundle from a blog row. */
function toPlatformBlog(blog: typeof blogs.$inferSelect): PlatformBlog {
  return {
    platform: blog.platform,
    wpUrl: blog.wpUrl,
    wpUsername: blog.wpUsername,
    wpAppPassword: blog.wpAppPassword,
    seoPlugin: blog.seoPlugin,
    shopifyAuthMode: blog.shopifyAuthMode,
    shopifyStoreUrl: blog.shopifyStoreUrl,
    shopifyAdminApiToken: blog.shopifyAdminApiToken,
    shopifyClientId: blog.shopifyClientId,
    shopifyClientSecret: blog.shopifyClientSecret,
  };
}

/**
 * Regenerate an already-published post in place: re-run generation for the
 * post's original topic/keywords (so it picks up the latest generator
 * improvements — heading de-dup, sentence-length cap, unique anchors, etc.)
 * and UPDATE the live external post at the same URL — no duplicate post.
 *
 * Pushes the new body + meta title/description via the existing in-place
 * update path. The featured image is left untouched; the regenerated body
 * carries its own fresh inline image.
 */
export async function regenerateAndUpdatePost(
  generatedPostId: string,
): Promise<GenerateAndPublishResult> {
  await requireAdmin();

  const [post] = await db
    .select()
    .from(generatedPosts)
    .where(eq(generatedPosts.id, generatedPostId))
    .limit(1);

  if (!post) throw new Error(`Generated post ${generatedPostId} not found`);
  if (post.status !== "published" || !post.externalPostId) {
    throw new Error(
      "Only a published post can be regenerated in place. Publish it first.",
    );
  }

  const ctx = await resolveIdeationContext(post.blogId);
  const blog = ctx.blog;
  if (!blogHasCredentials(blog)) {
    throw new Error(
      `Blog ${blog.domain} is missing ${blog.platform} credentials — reconnect the platform first`,
    );
  }

  const keywords = Array.isArray(post.keywords) ? (post.keywords as string[]) : [];
  // excludePostId: this post is published with a live URL (guard above), so
  // without it the regenerated body could link to itself.
  const internalLinkRefs = await getInternalLinkRefs(blog, {
    topic: post.topic,
    keywords,
    language: (post.language as "en" | "fr" | null) ?? ctx.language,
    excludePostId: post.id,
  });
  await loadNicheProfiles(); // generated niche context for getNicheContext()

  const content = await generateContent({
    topic: post.topic,
    keywords,
    wordCount: 1000,
    tone: "professional",
    niche: ctx.clientNiche,
    resolvedNiche: await resolveNicheConfig(ctx.clientNiche),
    customPrompt: ctx.customPrompt,
    applyPersona: ctx.applyPersona,
    seoOptimized: true,
    styleProfile: ctx.styleProfile ?? undefined,
    verticalKey: ctx.verticalKey,
    // Regeneration keeps the post's original language; only fall back to the
    // resolved next-language for legacy rows written before language was stored.
    language: (post.language as "en" | "fr" | null) ?? ctx.language,
    blogSeed: blog.id,
    blogDomain: blog.domain,
    internalLinkRefs,
    knowledgeSummaries: ctx.knowledge.summaries,
    cta: ctx.cta,
    brandName: blog.brandName,
    postId: post.id,
  });

  // Push the fresh body + meta to the SAME live post (same URL).
  const platformBlog = toPlatformBlog(blog);
  const shopifyBlogId =
    blog.platform === "shopify"
      ? (await resolveShopifyBlogId(platformBlog))?.blogId
      : undefined;

  const update = await backfillPostSeo(
    platformBlog,
    post.externalPostId,
    {
      bodyHtml: content.content,
      metaTitle: content.metaTitle,
      metaDescription: content.metaDescription,
      focusKeyword: content.keywords?.[0],
    },
    shopifyBlogId,
  );
  if (!update.success) {
    throw new Error(`Live update failed: ${update.message}`);
  }

  // Persist the new content on the existing row (status + external ids stay).
  await db
    .update(generatedPosts)
    .set({
      title: content.title,
      body: content.content,
      excerpt: content.excerpt,
      metaTitle: content.metaTitle,
      metaDescription: content.metaDescription,
      keywords: content.keywords,
      wordCount: content.wordCount,
      seoScore: content.seoScore,
      readabilityScore: content.readabilityScore,
      brandVoiceScore: content.brandVoiceScore,
      tokensUsed: content.tokensUsed,
      costUsd: String(content.costUsd),
      featuredImageUrl: content.heroImageUrl ?? null,
      bodyImageUrl: content.bodyImageUrl ?? null,
      scrubberReport: content.scrubberReport ?? null,
      flaggedForReview: content.flaggedForReview ?? false,
      generatedAt: new Date(),
      updatedAt: new Date(),
    })
    .where(eq(generatedPosts.id, post.id));

  return {
    success: true,
    generatedPostId: post.id,
    status: "published",
    // In-place regeneration of an already-live post. It never creates a new
    // row and never claims a day slot, so it has no transient path.
    transient: false,
    externalPostId: post.externalPostId,
    externalPostUrl: post.externalPostUrl ?? undefined,
    message: `Regenerated and updated the live post on ${blog.domain}`,
  };
}

/**
 * Resolve the shared ideation context for a blog (niche, locked style profile,
 * vertical/language, and distilled Knowledge Base) so the manual "Suggest"
 * actions anchor on exactly the same signals the auto-publish path uses.
 */
async function resolveIdeationContext(blogId: string) {
  const [row] = await db
    .select({
      blog: blogs,
      clientNiche: clients.niche,
      clientLanguageMode: clients.languageMode,
      clientCustomPrompt: clients.customPrompt,
      clientStackPersona: clients.stackPersona,
      ctaEnabled: clients.ctaEnabled,
      ctaLabel: clients.ctaLabel,
      ctaUrl: clients.ctaUrl,
      ctaPlacement: clients.ctaPlacement,
      ctaColor: clients.ctaColor,
    })
    .from(blogs)
    .innerJoin(clients, eq(blogs.clientId, clients.id))
    .where(eq(blogs.id, blogId))
    .limit(1);
  if (!row) throw new Error(`Blog ${blogId} not found`);
  const { blog, clientNiche } = row;
  const cta = effectiveBlogCta({
    niche: clientNiche,
    blogDomain: blog.domain,
    ctaEnabled: row.ctaEnabled,
    ctaLabel: row.ctaLabel,
    ctaUrl: row.ctaUrl,
    ctaPlacement: row.ctaPlacement,
    ctaColor: row.ctaColor,
  });
  // Custom prompts are client-wide; the persona-stack toggle is client-level.
  const customPrompt = row.clientCustomPrompt?.trim() || undefined;
  const applyPersona = Boolean(customPrompt) && Boolean(row.clientStackPersona);

  let styleProfile = await getStyleProfileForBlog(blog.id);
  if (!styleProfile) {
    const r = await assignProfileForBlogIfPeptides(blog.id);
    if (r.success && r.assigned) {
      styleProfile = await getStyleProfileForBlog(blog.id);
    }
  }

  const verticalForPost = verticalForNiche(clientNiche);
  const language = await resolveNextPostLanguage({
    languageMode: row.clientLanguageMode,
    blogId: blog.id,
    verticalLanguage: verticalForPost?.language,
    domain: blog.domain,
    niche: clientNiche,
  });
  const knowledge = await getActiveKnowledgeForBlog(blog.id);

  return {
    blog,
    clientNiche,
    customPrompt,
    applyPersona,
    styleProfile,
    verticalKey: verticalForPost?.key ?? null,
    language,
    knowledge,
    cta,
  };
}

/**
 * Manual "Suggest topic" button: ideate a topic (and matching keywords) for a
 * blog, anchored on its style profile + the client's Knowledge Base. The admin
 * can edit the result before generating the post.
 */
export async function suggestTopicForBlog(
  blogId: string,
): Promise<{ topic: string; keywords: string[] }> {
  await requireAdmin();
  const ctx = await resolveIdeationContext(blogId);
  const recentTitles = await getRecentTitles(blogId, ctx.blog.clientId);
  const ideated = await ideateTopic(ctx.clientNiche, recentTitles, {
    verticalKey: ctx.verticalKey,
    styleProfile: ctx.styleProfile ?? undefined,
    language: ctx.language,
    knowledge: ctx.knowledge,
    customPrompt: ctx.customPrompt,
    blogId,
  });
  if (ideated.exhausted) {
    // GeneratePostButton catches and toasts e.message — no component change.
    throw new Error(
      "Every demand-validated query for this blog is already covered. Refresh the client's keyword pool, then try again.",
    );
  }
  return { topic: ideated.topic, keywords: ideated.keywords };
}

/**
 * Manual "Suggest keywords" button: generate target keywords for the topic the
 * admin has typed (topic-aware), or niche/Knowledge-Base keywords when the
 * topic box is empty.
 */
export async function suggestKeywordsForBlog(
  blogId: string,
  topic?: string,
): Promise<string[]> {
  await requireAdmin();
  const ctx = await resolveIdeationContext(blogId);
  return suggestKeywords(ctx.clientNiche, topic ?? "", {
    knowledge: ctx.knowledge,
    language: ctx.language,
  });
}

export interface ReapResult {
  /** Rows released from 'generating' (nothing was sent to the platform). */
  generating: number;
  /** Rows released from 'publishing' (platform outcome unknown). */
  publishing: number;
  /** blog_keyword_targets rows returned to the pool. */
  keywordTargets: number;
  thresholdMinutes: number;
}

/**
 * Release rows abandoned mid-flight by a process that died (T08).
 *
 * A publish walks generated_posts.status through 'generating' →
 * 'publishing' → 'published', stamping updated_at at every transition.
 * Nothing legitimately stays in flight for long: a post takes ~25-35s
 * end-to-end and the route driving it is capped at maxDuration = 600s. The
 * default 30-minute threshold is 3x the longest possible legitimate lifetime.
 *
 * Rows only exceed it when the process is gone — a Render restart, a deploy
 * mid-run, an OOM, or the function hitting its deadline. Before T08 those
 * orphans were cosmetic because the due-check ignored in-flight rows
 * entirely. Now they HOLD the blog's day slot, so an unreaped row would block
 * that blog from publishing until midnight UTC. This is a prerequisite for
 * the guard, not hygiene.
 *
 * Idempotent and safe to run from all four shards concurrently: each
 * statement re-tests the age, so a row can only be reaped once.
 */
export async function reapStuckPublishes(
  thresholdMinutes = Number(process.env.PUBLISH_REAPER_MINUTES || "30"),
): Promise<ReapResult> {
  const cutoff = new Date(Date.now() - thresholdMinutes * 60_000);
  const now = new Date();

  // 'generating': nothing has been sent to the platform yet, so this is an
  // unambiguous failure. Safe to mark failed outright.
  const reapedGenerating = await db
    .update(generatedPosts)
    .set({
      status: "failed",
      failureReason: `Reaped after ${thresholdMinutes}m stuck in 'generating' (process restart or deploy mid-run)`,
      updatedAt: now,
    })
    .where(
      and(
        eq(generatedPosts.status, "generating"),
        lt(generatedPosts.updatedAt, cutoff),
      ),
    )
    .returning({ id: generatedPosts.id });

  // 'publishing': the article body is already persisted and the platform call
  // may or may not have landed before the process died. Park it as
  // 'generated' — "content exists, not live as far as we know" — rather than
  // 'failed'. That frees the day slot, keeps the draft publishable via
  // blog-actions.publishGeneratedPost, and does not assert an outcome we
  // cannot observe. It is the same status the ordinary publish-failure path
  // uses, so the dashboard already knows how to render it.
  //
  // Residual risk, accepted knowingly: if the process died in the few seconds
  // after WordPress/Shopify accepted the article but before the status
  // update, the post is live and netgrid does not know. Freeing the slot then
  // allows a second post that day. That is strictly rarer than the failure
  // mode this guards against (seconds on a process death, versus minutes on
  // every timeout), and the post-verification cron reconciles live posts back
  // into the record. Leaving 'publishing' rows in place would trade a rare
  // duplicate for a guaranteed permanent block on the blog.
  const reapedPublishing = await db
    .update(generatedPosts)
    .set({
      status: "generated",
      failureReason: `Reaped after ${thresholdMinutes}m stuck in 'publishing' — platform outcome unknown, verify the live site before re-publishing`,
      updatedAt: now,
    })
    .where(
      and(
        eq(generatedPosts.status, "publishing"),
        lt(generatedPosts.updatedAt, cutoff),
      ),
    )
    .returning({ id: generatedPosts.id });

  // The keyword ledger's own orphans. See T10 for the broader ledger work.
  const keywordTargets = await releaseStuckKeywordTargets();

  if (
    reapedGenerating.length > 0 ||
    reapedPublishing.length > 0 ||
    keywordTargets > 0
  ) {
    console.warn(
      `[auto-publish] reaper: released ${reapedGenerating.length} 'generating' + ` +
        `${reapedPublishing.length} 'publishing' post row(s) and ` +
        `${keywordTargets} keyword target(s) older than ${thresholdMinutes}m`,
    );
    recordPipelineError({
      site: "auto-publish.reaper",
      code: "PUBLISH_ROWS_REAPED",
      severity: "warn",
      message: `Reaped ${reapedGenerating.length} generating + ${reapedPublishing.length} publishing row(s) and ${keywordTargets} keyword target(s)`,
      context: {
        generating: reapedGenerating.length,
        publishing: reapedPublishing.length,
        keywordTargets,
        thresholdMinutes,
      },
    });
  }

  return {
    generating: reapedGenerating.length,
    publishing: reapedPublishing.length,
    keywordTargets,
    thresholdMinutes,
  };
}

export interface AutoPublishResult {
  considered: number;
  /** Total active blogs in DB before shard filter (when sharded). */
  totalActiveBlogs?: number;
  /** This service's shard index (0-based). Present only when sharding. */
  shardIndex?: number;
  /** Total parallel shards. Present only when sharding. */
  shardCount?: number;
  due: number;
  published: number;
  failed: number;
  skipped: number;
  /**
   * Blogs whose UTC-day publishing slot was already claimed by another
   * process — the idempotency guard firing (T08). Included in `skipped`.
   * Should be 0 in steady state; anything above 0 means a shard was invoked
   * twice, so alert on it.
   */
  claimLost: number;
  /** In-flight rows released at the start of this sweep. */
  reaped: ReapResult;
  deferred: number; // due but capped this run; will run next cron tick
  /**
   * Active blogs — network-wide, NOT shard-filtered — whose posting_plan is
   * empty. These can never publish and are excluded from the candidate query
   * entirely. This is a configuration fault, surfaced as a critical item in
   * /api/notifications and as an activity_log row written by shard 0.
   */
  unscheduledActiveBlogs: number;
  /** Domains of those blogs, capped at 25 so the log line stays readable. */
  unscheduledDomains: string[];
  /** True when ?dry=1 was passed: the queue was built but nothing published. */
  dryRun: boolean;
  currentHourUtc: number;
  maxPerRun: number;
  results: Array<{
    blogId: string;
    domain: string;
    preferredHour: number;
    status:
      | "published"
      | "generated"
      | "failed"
      | "skipped"
      | "deferred"
      | "dry_run";
    message: string;
  }>;
  /**
   * cron_runs.id for this invocation. The durable record lives in Postgres
   * whether or not anyone reads this response; this is the join key into
   * pipeline_errors. Undefined only when TELEMETRY_ENABLED=0.
   */
  runId?: string;
  /** Full per-run counter set — mirrors cron_runs.counters. */
  counters?: RunCounters;
}

/**
 * Cron-triggered sweep. Designed for a network of many blogs where multiple
 * blogs may be due on the same day — we don't want them all hitting the
 * publish path at the same moment.
 *
 * Phases:
 *
 *   1. Load all active blogs with cadence configured, joined to client.
 *   2. For each blog, determine eligibility:
 *        a. Client total-posts cap (clients.totalBlogsTarget)
 *        b. Cadence: today's entry in blogs.posting_plan is non-zero AND
 *           today's published count is below it (see isBlogDueForPost)
 *        c. Time-of-day slot: current UTC hour ≥ preferredHourForBlog(blogId).
 *           This spreads publishes naturally across the day — a blog whose
 *           slot is 09:00 UTC waits until the cron sees hour 9, then is
 *           processed at the first available opportunity.
 *        d. Credentials present
 *   3. Sort the eligible queue by lastPostVerifiedAt ASC NULLS FIRST so
 *      the blog that hasn't posted in the longest is processed first
 *      (priority = "most overdue first"). Tie-break by preferred hour.
 *   4. Take the top MAX_BLOGS_PER_CRON_RUN. Anything beyond that is marked
 *      "deferred" and processed on the next cron run — prevents a single
 *      run from monopolizing maxDuration (300s).
 *   5. Process sequentially. Each blog takes ~25-35s end-to-end; running
 *      them in serial avoids API rate-limit contention against Anthropic,
 *      Google AI Studio, Shopify, and WordPress at the same instant.
 *
 * In-memory counters update as we go so subsequent blogs in the same run
 * see correct per-client totals and per-blog daily counts.
 */
/**
 * Sharding params — validated + defaulted. When shardCount<=1 the shard
 * filter is a no-op (every blog is in shard 0). Extracted so the telemetry
 * wrapper can label the run with the same values the body uses.
 */
function resolveShard(opts: { shardIndex?: number; shardCount?: number }): {
  shardIndex: number;
  shardCount: number;
} {
  // THROW on anything malformed instead of defaulting (T08).
  //
  // The old code silently coerced a bad value to shardIndex 0 / shardCount 1.
  // Because these arrive from a query string baked into each cron service's
  // CRON_PATH env var, a single mistyped character had two silent failure
  // modes, both of which double-publish:
  //
  //   "?shrad=0&shardCount=4" → index 0, count 4 → this service duplicates
  //                             the real shard-0 service: a quarter of the
  //                             network published twice every hour.
  //   "?shard=o&shardCount=4" → count falls back to 1 → the shard filter
  //                             becomes a no-op and this ONE service
  //                             publishes the ENTIRE network, on top of all
  //                             four real shards.
  //
  // Neither showed up in the response body or the logs (the shard diagnostic
  // is suppressed when shardCount <= 1, so the worse case was the quieter
  // one). The route validates these too and answers 400; this throw is the
  // defence in depth for any other caller.
  if ((opts.shardIndex === undefined) !== (opts.shardCount === undefined)) {
    throw new Error(
      "auto-publish sharding: shardIndex and shardCount must be supplied together " +
        `(got shardIndex=${String(opts.shardIndex)}, shardCount=${String(opts.shardCount)})`,
    );
  }
  const shardCount = opts.shardCount ?? 1;
  const shardIndex = opts.shardIndex ?? 0;
  if (!Number.isInteger(shardCount) || shardCount < 1) {
    throw new Error(
      `auto-publish sharding: shardCount must be an integer >= 1, got ${String(opts.shardCount)}`,
    );
  }
  if (
    !Number.isInteger(shardIndex) ||
    shardIndex < 0 ||
    shardIndex >= shardCount
  ) {
    throw new Error(
      `auto-publish sharding: shardIndex must be an integer in [0, ${shardCount - 1}], got ${String(opts.shardIndex)}`,
    );
  }
  return { shardIndex, shardCount };
}

export async function runAutoPublishCron(
  opts: {
    /** This cron service's shard index (0-based). Default 0 = no sharding. */
    shardIndex?: number;
    /** Total number of parallel cron services. Default 1 = no sharding. */
    shardCount?: number;
    /**
     * Build the eligibility queue and return it WITHOUT publishing anything.
     * Used to inspect cadence decisions safely (T17 SOP section 8.3).
     * Reached via /api/cron/auto-publish?dry=1.
     */
    dryRun?: boolean;
  } = {},
): Promise<AutoPublishResult> {
  const { shardIndex, shardCount } = resolveShard(opts);
  // The wrapper persists exactly one cron_runs row plus every
  // pipeline_errors buffered inside, whether the body resolves or throws.
  return runWithTelemetry(
    {
      job: "auto-publish",
      shardIndex: shardCount > 1 ? shardIndex : null,
      shardCount: shardCount > 1 ? shardCount : null,
    },
    () => runAutoPublishCronInner(opts),
  );
}

async function runAutoPublishCronInner(
  opts: { shardIndex?: number; shardCount?: number; dryRun?: boolean } = {},
): Promise<AutoPublishResult> {
  const now = new Date();
  const todayStart = startOfUtcDay(now);
  const todayKey = utcDayKey(now);
  const currentHour = now.getUTCHours();
  const { shardIndex, shardCount } = resolveShard(opts);

  // 0. Release anything stuck in flight from a previous run BEFORE counting.
  //    An in-flight row now holds the blog's day slot, so counting first
  //    would skip that blog for the rest of the UTC day.
  const reaped = await reapStuckPublishes();

  // 1. Active blogs that have a real schedule. Blogs with an empty
  //    posting_plan are EXCLUDED here rather than loaded and skipped every
  //    hour — they are counted and alerted on separately below.
  //    Sort at the DB layer by lastPostVerifiedAt ASC NULLS FIRST so we can
  //    stream longest-waiting first without an in-memory sort pass.
  const rows = await db
    .select({
      blog: blogs,
      clientNiche: clients.niche,
      clientTarget: clients.totalBlogsTarget,
    })
    .from(blogs)
    .innerJoin(clients, eq(blogs.clientId, clients.id))
    .where(
      and(
        eq(blogs.status, "active"),
        // Exclude PAUSED clients only (7073a237's intent: "a paused client's
        // blogs are skipped"). The original implementation required
        // status='active', but every client in this deployment is
        // 'onboarding' — the gate as written silently stopped ALL publishing
        // the day it deployed (Aug 31). Onboarding clients have always
        // published; paused is the only exclusion.
        ne(clients.status, "paused"),
        sql`${blogs.postingPlan} <> '{0,0,0,0,0,0,0}'::integer[]`,
      ),
    )
    .orderBy(
      sql`${blogs.lastPostVerifiedAt} ASC NULLS FIRST`,
      asc(blogs.id),
    );

  // 1b. The alertable condition: active blogs that can never publish.
  //     Network-wide on purpose — this is a configuration fault, not a
  //     per-shard workload figure. Uses the blogs_unscheduled_idx partial
  //     index added by 0043_posting_plan.sql. Paused clients are excluded
  //     for the same reason they are excluded above: their blogs are not
  //     meant to be publishing, so an empty plan there is not a fault.
  const unscheduledRows = await db
    .select({ id: blogs.id, domain: blogs.domain })
    .from(blogs)
    .innerJoin(clients, eq(blogs.clientId, clients.id))
    .where(
      and(
        eq(blogs.status, "active"),
        ne(clients.status, "paused"),
        sql`${blogs.postingPlan} = '{0,0,0,0,0,0,0}'::integer[]`,
      ),
    )
    .orderBy(asc(blogs.domain));

  // Only shard 0 reports, so four hourly cron services don't quadruple the
  // log noise and the activity_log rows.
  if (shardIndex === 0 && unscheduledRows.length > 0) {
    const domains = unscheduledRows.map((r) => r.domain);
    console.warn(
      `[auto-publish][ALERT] ${unscheduledRows.length} active blog(s) have no ` +
        `posting plan and will never publish: ${domains.slice(0, 25).join(", ")}` +
        (domains.length > 25 ? `, +${domains.length - 25} more` : ""),
    );
    await logActivity({
      action: "auto_publish_unscheduled",
      entityType: "blog",
      details: {
        count: unscheduledRows.length,
        domains: domains.slice(0, 50),
      },
    });
  }

  // 2. Per-client + per-blog usage counters.
  const clientCounts = await db
    .select({
      clientId: generatedPosts.clientId,
      n: sql<number>`count(*)::int`,
    })
    .from(generatedPosts)
    .where(eq(generatedPosts.status, "published"))
    .groupBy(generatedPosts.clientId);
  const publishedByClient = new Map(clientCounts.map((r) => [r.clientId, r.n]));

  // Per-blog "posts that occupy today" count. This drives isBlogDueForPost
  // below, so what it counts decides whether a blog publishes again today.
  //
  // It MUST include in-flight rows (T08). The old version filtered on
  // status='published' AND published_at >= todayStart; a post another sweep
  // is mid-way through writing is 'generating' or 'publishing' with a NULL
  // published_at, so it failed BOTH predicates and the blog looked due again.
  // That is the double-post.
  //
  // Two arms, because a row can carry its day either way:
  //   publish_day = today — an auto-publish claim (set at insert time, so it
  //                         is visible from the first millisecond of the run,
  //                         long before published_at exists).
  //   publish_day IS NULL — a manual post from the admin UI, plus every
  //                         pre-T08 row. Those are only countable through
  //                         published_at, exactly as before.
  //
  // 'generated' and 'failed' stay excluded: a run that failed, or wrote an
  // article the platform refused, has not used up the blog's day.
  const blogCountsToday = await db
    .select({
      blogId: generatedPosts.blogId,
      n: sql<number>`count(*)::int`,
    })
    .from(generatedPosts)
    .where(
      and(
        inArray(generatedPosts.status, ["generating", "publishing", "published"]),
        or(
          eq(generatedPosts.publishDay, todayKey),
          and(
            isNull(generatedPosts.publishDay),
            gte(generatedPosts.publishedAt, todayStart),
          ),
        ),
      ),
    )
    .groupBy(generatedPosts.blogId);
  const publishedTodayByBlog = new Map(blogCountsToday.map((r) => [r.blogId, r.n]));

  // Per-blog REAL last-publish timestamp = MAX(published_at) over our own
  // published posts. This is the source of truth for the safety floor and
  // the "brand-new blog" check — NOT blogs.lastPostVerifiedAt, which the
  // post-verification cron resets every 6h (and would otherwise make the
  // safety floor permanently skip blogs that haven't actually re-posted).
  const lastPublishedRows = await db
    .select({
      blogId: generatedPosts.blogId,
      lastPublishedAt: sql<Date | null>`max(${generatedPosts.publishedAt})`,
    })
    .from(generatedPosts)
    .where(eq(generatedPosts.status, "published"))
    .groupBy(generatedPosts.blogId);
  const lastPublishedByBlog = new Map(
    lastPublishedRows.map((r) => [
      r.blogId,
      r.lastPublishedAt ? new Date(r.lastPublishedAt) : null,
    ]),
  );

  // 3. Determine eligibility for each blog. Build the run queue + the
  //    skip list in one pass so the final result reports both.
  interface QueueEntry {
    blog: typeof blogs.$inferSelect;
    clientTarget: number | null;
    preferredHour: number;
    todayCount: number;
    clientCount: number;
    lastPublishedAt: Date | null;
  }
  const queue: QueueEntry[] = [];
  const results: AutoPublishResult["results"] = [];
  let skipped = 0;

  // Filter the candidate list to this shard. When shardCount=1 every
  // row passes (no-op). When >1, each blog is in exactly one shard.
  const shardFilteredRows =
    shardCount <= 1
      ? rows
      : rows.filter(
          (r) => shardForBlog(r.blog.id, shardCount) === shardIndex,
        );

  if (shardCount > 1) {
    console.info(
      `[auto-publish] shard ${shardIndex + 1}/${shardCount} — ` +
        `${shardFilteredRows.length} of ${rows.length} active blogs assigned to this shard`,
    );
  }

  for (const { blog, clientTarget } of shardFilteredRows) {
    const preferredHour = preferredHourForBlog(blog.id);
    const todayCount = publishedTodayByBlog.get(blog.id) ?? 0;
    const clientCount = publishedByClient.get(blog.clientId) ?? 0;
    // Real last-publish time from OUR publish history (not the
    // verification timestamp). null = we have never published to this
    // blog through the system.
    const lastPublishedAt = lastPublishedByBlog.get(blog.id) ?? null;

    // 3a. Client total cap
    if (clientTarget && clientTarget > 0 && clientCount >= clientTarget) {
      skipped++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        preferredHour,
        status: "skipped",
        message: `client total-posts cap hit (${clientCount}/${clientTarget}) — increase clients.totalBlogsTarget to resume`,
      });
      continue;
    }

    // 3b. Cadence (weekday + daily-cap + min hours)
    const decision = isBlogDueForPost(blog, todayCount, now, lastPublishedAt);
    if (!decision.due) {
      skipped++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        preferredHour,
        status: "skipped",
        message: decision.reason,
      });
      continue;
    }

    // 3c. Time-of-day slot. Wait until the cron sees the blog's preferred
    //     hour or later. Blocks before-hours publishes; once hour is
    //     reached, the blog is eligible for the rest of the day.
    //
    //     EXCEPTION: brand-new blogs (never published through our system)
    //     bypass the slot check on their first eligible weekday so they
    //     don't sit idle for up to 23h waiting for their slot. We use
    //     OUR publish history (lastPublishedAt), NOT lastPostVerifiedAt,
    //     so a blog with pre-existing live posts that the verification
    //     cron stamped still counts as new to the auto-publisher.
    if (lastPublishedAt && currentHour < preferredHour) {
      skipped++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        preferredHour,
        status: "skipped",
        message: `current hour ${currentHour}h UTC < preferred hour ${preferredHour}h UTC`,
      });
      continue;
    }

    // 3d. Credentials
    if (!blogHasCredentials(blog)) {
      skipped++;
      results.push({
        blogId: blog.id,
        domain: blog.domain,
        preferredHour,
        status: "skipped",
        message: `missing ${blog.platform} credentials`,
      });
      continue;
    }

    queue.push({
      blog,
      clientTarget,
      preferredHour,
      todayCount,
      clientCount,
      lastPublishedAt,
    });
  }

  // 4. Sort + apply per-run cap.
  //
  //    Sort priority:
  //      a. lastPostVerifiedAt ASC NULLS FIRST — oldest-waiting
  //         blogs (and brand-new blogs with null) jump the line over
  //         freshly-posted ones.
  //      b. Tie-break by blog UUID for stable ordering.
  //
  //    Anything beyond MAX_BLOGS_PER_CRON_RUN is "deferred" — those
  //    blogs become eligible again on the next cron tick.
  queue.sort((a, b) => {
    // 1. Oldest publish DAY first (null = never published → goes first).
    //    Bucketing to the UTC day rather than the exact timestamp is what
    //    makes the runway tie-break below actually fire: two blogs that
    //    both last published "on Tuesday" now compare equal here.
    const aDay = a.lastPublishedAt
      ? startOfUtcDay(a.lastPublishedAt).getTime()
      : 0;
    const bDay = b.lastPublishedAt
      ? startOfUtcDay(b.lastPublishedAt).getTime()
      : 0;
    if (aDay !== bDay) return aDay - bDay;
    // 2. Least runway left today first. A blog whose slot is 17h has one
    //    tick before the UTC day rolls over and its scheduled day is gone
    //    (strict day-only cadence, no catch-up); a blog whose slot is 2h
    //    has fifteen. Highest preferred hour therefore goes first.
    if (a.preferredHour !== b.preferredHour) {
      return b.preferredHour - a.preferredHour;
    }
    // 3. Stable tie-break.
    return a.blog.id.localeCompare(b.blog.id);
  });
  const toRun = queue.slice(0, MAX_BLOGS_PER_CRON_RUN);
  const deferredQueue = queue.slice(MAX_BLOGS_PER_CRON_RUN);
  for (const entry of deferredQueue) {
    results.push({
      blogId: entry.blog.id,
      domain: entry.blog.domain,
      preferredHour: entry.preferredHour,
      status: "deferred",
      message: `over per-run cap (${MAX_BLOGS_PER_CRON_RUN}) — will run on the next cron tick`,
    });
  }

  if (toRun.length > 0) {
    console.info(
      `[auto-publish] hour=${currentHour}h UTC, considered=${rows.length}, eligible=${queue.length}, running=${toRun.length}, deferred=${deferredQueue.length}, skipped=${skipped}`,
    );
    console.info(
      `[auto-publish] run order: ${toRun
        .map(
          (e, i) =>
            `${i + 1}. ${e.blog.domain} (slot=${e.preferredHour}h, lastPublished=${e.lastPublishedAt?.toISOString() ?? "never"})`,
        )
        .join(" | ")}`,
    );
  }

  // 4b. Dry run: report what WOULD happen and stop. Nothing is generated,
  //     nothing is published, no counters move.
  if (opts.dryRun) {
    for (const entry of toRun) {
      results.push({
        blogId: entry.blog.id,
        domain: entry.blog.domain,
        preferredHour: entry.preferredHour,
        status: "dry_run",
        message: `would publish (plan ${formatPostingPlan(
          normalizePostingPlan(entry.blog.postingPlan),
        )}, slot ${entry.preferredHour}h UTC)`,
      });
    }
    return {
      considered: shardCount > 1 ? shardFilteredRows.length : rows.length,
      ...(shardCount > 1
        ? { totalActiveBlogs: rows.length, shardIndex, shardCount }
        : {}),
      due: queue.length,
      published: 0,
      failed: 0,
      skipped,
      claimLost: 0,
      reaped,
      deferred: deferredQueue.length,
      unscheduledActiveBlogs: unscheduledRows.length,
      unscheduledDomains: unscheduledRows.slice(0, 25).map((r) => r.domain),
      dryRun: true,
      currentHourUtc: currentHour,
      maxPerRun: MAX_BLOGS_PER_CRON_RUN,
      results,
    };
  }

  // 5. Process the run queue with a concurrency-capped worker pool.
  //
  //    Default 3 concurrent publishes per cron tick. With 4 shards
  //    running hourly this gives 12 simultaneous in-flight publishes
  //    across the network — safe vs. Anthropic's 50 RPM (3 Claude
  //    calls/post × 12 = 36 RPM peak) and Google's 60 RPM (2 image
  //    calls/post × 12 = 24 RPM peak).
  //
  //    Override via AUTO_PUBLISH_CONCURRENCY env var on the web service.
  //    Set to 1 to restore old sequential behaviour for debugging.
  //
  //    Per-blog retry: transient errors (rate limits, 5xx, network)
  //    retry once inside the same tick. Permanent errors (validation,
  //    auth) bail immediately.
  //
  //    JS is single-threaded — Map operations are atomic without locks,
  //    so publishedTodayByBlog / publishedByClient updates are safe
  //    even with parallel workers.
  let published = 0;
  let failed = 0;
  // Counts the idempotency guard firing (T08). Also folded into `skipped`.
  let claimLost = 0;

  const concurrency = Math.max(
    1,
    Math.min(
      8,
      Number(process.env.AUTO_PUBLISH_CONCURRENCY || "3"),
    ),
  );

  async function publishOne(entry: QueueEntry): Promise<void> {
    const { blog } = entry;
    // Everything below — generateContent, the image pipeline, publishPost,
    // the detached IndexNow ping — records against THIS blog. withBlog
    // shares the counters and error buffer by reference, so parallel
    // workers accumulate into one run while attribution stays per-blog.
    return withBlog(
      { blogId: blog.id, clientId: blog.clientId, domain: blog.domain },
      () => publishOneInner(entry),
    );
  }

  async function publishOneInner(entry: QueueEntry): Promise<void> {
    const { blog, todayCount, clientCount, preferredHour } = entry;
    let lastError: unknown = null;
    let lastMessage = "Unknown error";

    // Up to 2 attempts. Sleep 8s between them so a transient Anthropic
    // 429 has time to release budget. The publish action itself has
    // internal retries against Anthropic/Google, so this is the
    // outermost belt + suspenders.
    //
    // The retry decision reads BOTH channels, and that is the whole point
    // (T08): runGenerateAndPublish catches its own errors from the pending
    // insert onward and RETURNS { status: "failed", transient }. Only the
    // pre-flight section (blog lookup, credentials, ideation, the claim
    // insert) can throw. The old code inspected thrown errors only, so the
    // dominant failure class — an Anthropic 429 during generation — never
    // retried at all.
    for (let attempt = 1; attempt <= 2; attempt++) {
      try {
        if (attempt > 1) {
          await new Promise((r) => setTimeout(r, 8000));
        }
        const result = await runGenerateAndPublish({
          blogId: blog.id,
          isAutoGenerated: true,
        });

        // Retry only a transient HARD failure. A "generated" result means the
        // article exists and only the platform call failed — regenerating
        // would pay Anthropic and Google twice and orphan the first draft, so
        // it is left for blog-actions.publishGeneratedPost. A "skipped"
        // result means another run owns the slot; retrying would just lose
        // the race again.
        if (result.status === "failed" && result.transient && attempt < 2) {
          lastMessage = result.message;
          console.warn(
            `[auto-publish] transient failure for ${blog.domain}, retrying in 8s: ${result.message.slice(0, 200)}`,
          );
          continue;
        }

        results.push({
          blogId: blog.id,
          domain: blog.domain,
          preferredHour,
          status: result.status,
          message: result.message,
        });
        if (result.status === "published") {
          published++;
          publishedTodayByBlog.set(blog.id, todayCount + 1);
          publishedByClient.set(blog.clientId, clientCount + 1);
        } else if (result.status === "skipped") {
          // Lost the day-slot claim: another process is already publishing
          // for this blog today. Not a failure — the guard did its job.
          skipped++;
          claimLost++;
        } else {
          failed++;
        }
        return;
      } catch (error) {
        // Thrown errors can only come from the pre-flight section. Same
        // classifier, so behaviour for those is unchanged.
        lastError = error;
        lastMessage = error instanceof Error ? error.message : "Unknown error";
        if (!isTransientFailure(lastMessage)) break;
      }
    }

    failed++;
    const message = lastMessage;
    recordPipelineError({
      site: "auto-publish.publishOne",
      code: "PUBLISH_ATTEMPT_FAILED",
      severity: "error",
      message: `Auto-publish failed for ${blog.domain} after retry: ${message}`,
      context: {
        domain: blog.domain,
        platform: blog.platform,
        preferredHour,
        stack: lastError instanceof Error ? lastError.stack?.slice(0, 2000) : null,
      },
    });
    results.push({
      blogId: blog.id,
      domain: blog.domain,
      preferredHour,
      status: "failed",
      message,
    });
  }

  let cursor = 0;
  async function worker(): Promise<void> {
    while (true) {
      const i = cursor++;
      if (i >= toRun.length) return;
      await publishOne(toRun[i]);
    }
  }

  console.info(
    `[auto-publish] starting ${toRun.length} blogs with concurrency=${concurrency}`,
  );
  await Promise.all(
    Array.from({ length: Math.min(concurrency, toRun.length) }, () => worker()),
  );

  const considered = shardCount > 1 ? shardFilteredRows.length : rows.length;
  // Mirror the run-level numbers into the durable counter set. The deep
  // counters (truncatedSalvaged, imageless, providerUsed, ...) were already
  // bumped in place by the generator during publishOne.
  setCounter("considered", considered);
  setCounter("due", queue.length);
  setCounter("published", published);
  setCounter("failed", failed);
  setCounter("skipped", skipped);
  setCounter("deferred", deferredQueue.length);
  setCounter("claimLost", claimLost);

  return {
    // When sharded, "considered" is the count this shard saw after
    // filtering; totalActiveBlogs is the full network size.
    considered,
    ...(shardCount > 1
      ? {
          totalActiveBlogs: rows.length,
          shardIndex,
          shardCount,
        }
      : {}),
    due: queue.length,
    published,
    failed,
    skipped,
    claimLost,
    reaped,
    deferred: deferredQueue.length,
    unscheduledActiveBlogs: unscheduledRows.length,
    unscheduledDomains: unscheduledRows.slice(0, 25).map((r) => r.domain),
    dryRun: false,
    currentHourUtc: currentHour,
    maxPerRun: MAX_BLOGS_PER_CRON_RUN,
    results,
    runId: currentRunId(),
    counters: snapshotCounters(),
  };
}